name: Deploy to Azure VM

on:
  push:
    branches:
      - dev # Adjust the branch as needed

jobs:
  deploy:
    name: Deploy React/Vite App to Azure VM
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18' # Use your desired Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Build the project
      run: npm run build # Ensure this is the correct command for Vite

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: dist/ # Path to the build directory

    - name: Copy files to VM
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VM_IP }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: ./dist/
        target: /var/www/myapp/ # Path on your VM

    - name: Restart application
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
# Navigate to the application directory
        cd /var/www/myapp/ || exit 1  # Exit if cd fails

# Restart the application; if it fails, start it
        pm2 restart myapp || pm2 start npm --name "myapp" -- start

# Optional: Print a success 
        echo "Application restarted successfully."
        EOF

        # ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
        #   # Commands to restart your application
        #   cd /var/www/myapp/
        #   pm2 restart myapp || pm2 start npm --name "myapp" -- start
        # EOF
