name: Deploy to Azure VM

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies and build the project
      run: |
        npm install
        npm run build

    # Store the SSH key in a file
    - name: Set up SSH key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
        chmod 600 ~/.ssh/deploy_key

    - name: Clean target directory on VM
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_IP }} 'rm -rf /var/www/myapp/dist'

    - name: Copy files to VM using rsync
      run: |
        rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key" ./dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_IP }}:/var/www/myapp/dist/
    
    - name: Restart Nginx on VM
      run: |
        ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_IP }} 'sudo systemctl restart nginx'



# name: Deploy to Azure VM

# on:
#   push:
#     branches:
#       - dev # Adjust the branch as needed

# jobs:
#   deploy:
#     name: Deploy React/Vite App to Azure VM
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v3

#     - name: Set up Node.js
#       uses: actions/setup-node@v3
#       with:
#         node-version: '18' # Use your desired Node.js version

#     - name: Install dependencies
#       run: npm ci

#     - name: Build the project
#       run: npm run build # Ensure this is the correct command for Vite

#     - name: Upload build artifacts
#       uses: actions/upload-artifact@v3
#       with:
#         name: build
#         path: dist/ # Path to the build directory

#     - name: Copy files to VM
#       uses: appleboy/scp-action@v0.1.4
#       with:
#         host: ${{ secrets.VM_IP }}
#         username: ${{ secrets.SSH_USERNAME }}
#         key: ${{ secrets.SSH_PRIVATE_KEY }}
#         source: ./dist/
#         target: /var/www/myapp/ # Path on your VM

#     - name: Restart application
#       run: |
#         ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_IP }} << 'EOF'
#           # Commands to restart your application
#           cd /var/www/myapp/
#           pm2 restart myapp || pm2 start npm --name "myapp" -- start
#         EOF
