name: Build and Push Docker Image

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t cleowoman/mytemp:latest .

    - name: Push Docker image
      run: |
        docker push cleowoman/mytemp:latest


# name: Deploy to Azure VM

# on:
#   push:
#     branches:
#       - dev

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Install dependencies and build the project
#       run: |
#         npm install
#         npm run build

#     # Set up SSH key
#     - name: Set up SSH key
#       run: |
#         mkdir -p ~/.ssh
#         echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
#         chmod 600 ~/.ssh/deploy_key

#     # Clean target directory on VM
#     - name: Clean target directory on VM
#       run: |
#         ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_IP }} 'sudo rm -rf /var/www/myapp/dist/*'

#     # Copy files to VM using rsync
#     - name: Copy files to VM using rsync
#       run: |
#         rsync -avz --delete -e "ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key" ./dist/ ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_IP }}:/var/www/myapp/dist/
    
#     # Restart Nginx on VM
#     - name: Restart Nginx on VM
#       run: |
#         ssh -o StrictHostKeyChecking=no -i ~/.ssh/deploy_key ${{ secrets.SSH_USERNAME }}@${{ secrets.VM_IP }} 'sudo systemctl restart nginx'



